name: Build and Push Docker Image

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME} \
            --build-arg DOCKERHUB_TOKEN=${DOCKERHUB_TOKEN} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest -f path/to/Dockerfile .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest
